### ISSUE TITLE
在 Clash for Windows 中使用 Mixin 配置覆盖全局规则

### ISSUE THREAD

**Issue by Mrered** [Loyalsoldier/clash-rules#174]
如果你想让你所有的流量都按照一个固定的模式进行分流，那么可以考虑看看下面的内容：

## 1 下载所有文件

[Releases · Loyalsoldier/clash-rules](https://github.com/Loyalsoldier/clash-rules/releases)

## 2 重命名文件

重命名为`.yaml`

## 3 移动文件

将上述文件移动到一个 `<你喜欢的位置>`

这里以macOS为例，我移动到了 `~/.config/clash/providers/rule/`

## 4 修改混合模式配置

在混合模式配置中覆盖填入

```yaml
mixin:
    rule-providers:
        reject:
            type: file
            behavior: domain
            path: ./providers/rule/reject.yaml
            interval: 86400
        icloud:
            type: file
            behavior: domain
            path: ./providers/rule/icloud.yaml
            interval: 86400
        apple:
            type: file
            behavior: domain
            path: ./providers/rule/apple.yaml
            interval: 86400
        google:
            type: file
            behavior: domain
            path: ./providers/rule/google.yaml
            interval: 86400
        proxy:
            type: file
            behavior: domain
            path: ./providers/rule/proxy.yaml
            interval: 86400
        direct:
            type: file
            behavior: domain
            path: ./providers/rule/direct.yaml
            interval: 86400
        private:
            type: file
            behavior: domain
            path: ./providers/rule/private.yaml
            interval: 86400
        gfw:
            type: file
            behavior: domain
            path: ./providers/rule/gfw.yaml
            interval: 86400
        greatfire:
            type: file
            behavior: domain
            path: ./providers/rule/greatfire.yaml
            interval: 86400
        tld-not-cn:
            type: file
            behavior: domain
            path: ./providers/rule/tld-not-cn.yaml
            interval: 86400
        telegramcidr:
            type: file
            behavior: ipcidr
            path: ./providers/rule/telegramcidr.yaml
            interval: 86400
        cncidr:
            type: file
            behavior: ipcidr
            path: ./providers/rule/cncidr.yaml
            interval: 86400
        lancidr:
            type: file
            behavior: ipcidr
            path: ./providers/rule/lancidr.yaml
            interval: 86400
        applications:
            type: file
            behavior: classical
            path: ./providers/rule/applications.yaml
            interval: 86400

    rules:
        - RULE-SET,applications,DIRECT
        - DOMAIN,clash.razord.top,DIRECT
        - DOMAIN,yacd.haishan.me,DIRECT
        - RULE-SET,private,DIRECT
        - RULE-SET,reject,REJECT
        - RULE-SET,tld-not-cn,♻️ 自动选择
        - RULE-SET,gfw,♻️ 自动选择
        - RULE-SET,greatfire,♻️ 自动选择
        - RULE-SET,telegramcidr,Proxy
        - DOMAIN-KEYWORD,speed.neu6.edu.cn,DIRECT
        - DOMAIN-KEYWORD,myip4.ipip.net,DIRECT
        - DOMAIN-KEYWORD,test-ipv6,DIRECT
        - MATCH,DIRECT
```

**Comment by DK05310214** [comment]
Can "Clash for Windows" download the required rulseset-file automatically？

**Comment by Loyalsoldier** [comment]
> Can "Clash for Windows" download the required rulseset-file automatically？

Just use the ruleset files like this:

```
mixin:
  rule-providers:
    proxy:
      type: http
      behavior: domain
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
      path: ./providers/rule/proxy.yaml
      interval: 86400
```
