### ISSUE TITLE
Clash New text format

### ISSUE THREAD

**Issue by Tirbod** [Loyalsoldier/clash-rules#177]
### Description
if new rule-provider [text format](https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#domain) could [improve matching performance](https://lancellc.gitbook.io/clash/clash-config-file/rule-provider#format),it would be great if rules will be in txt format.
### Example
```
  reject:
    type: http
    behavior: domain
    format: 'text'
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.txt
    interval: 86400
```
current reject.txt in text format:
[reject.txt](https://github.com/Loyalsoldier/clash-rules/files/11314810/reject.txt)
