### ISSUE TITLE
请问这个规则列表会怎样自动更新

### ISSUE THREAD

**Issue by q2051839** [Loyalsoldier/clash-rules#178]
我试着更新clash订阅，这个缓存的TXT列表还是旧版本。如何触发它的自动更新

**Comment by Loyalsoldier** [comment]
```
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
```

interval 86400 就是更新的间隔秒数，设置了 24 小时自动更新。
