### ISSUE TITLE
提供一种parser可以自动替换订阅的规则为自定义规则

### ISSUE THREAD

**Issue by Jie-Qiao** [Loyalsoldier/clash-rules#27]
首先在parser中，使用reg来匹配所有url，或者自定义url均可：
```js
parsers: # array
  - reg: .*$
    file: "path/to/parser.js"
```

在parser.js中可以这样写：

```js
module.exports.parse = async (raw, { axios, yaml, notify, console }, { name, url, interval, selected }) => {
    var obj = yaml.parse(raw)
    var first_name=obj['proxy-groups'][0]['name']

    var rules=["PROCESS-NAME,v2ray,DIRECT",
    "PROCESS-NAME,xray,DIRECT",
    "PROCESS-NAME,naive,DIRECT",
    "PROCESS-NAME,trojan,DIRECT",
    "PROCESS-NAME,trojan-go,DIRECT",
    "PROCESS-NAME,ss-local,DIRECT",
    "PROCESS-NAME,privoxy,DIRECT",
    "PROCESS-NAME,leaf,DIRECT",
    "PROCESS-NAME,v2ray.exe,DIRECT",
    "PROCESS-NAME,xray.exe,DIRECT",
    "PROCESS-NAME,naive.exe,DIRECT",
    "PROCESS-NAME,trojan.exe,DIRECT",
    "PROCESS-NAME,trojan-go.exe,DIRECT",
    "PROCESS-NAME,ss-local.exe,DIRECT",
    "PROCESS-NAME,privoxy.exe,DIRECT",
    "PROCESS-NAME,leaf.exe,DIRECT",
    "PROCESS-NAME,Surge,DIRECT",
    "PROCESS-NAME,Surge 2,DIRECT",
    "PROCESS-NAME,Surge 3,DIRECT",
    "PROCESS-NAME,Surge 4,DIRECT",
    "PROCESS-NAME,Surge%202,DIRECT",
    "PROCESS-NAME,Surge%203,DIRECT",
    "PROCESS-NAME,Surge%204,DIRECT",
    "PROCESS-NAME,Thunder,DIRECT",
    "PROCESS-NAME,DownloadService,DIRECT",
    "PROCESS-NAME,qBittorrent,DIRECT",
    "PROCESS-NAME,Transmission,DIRECT",
    "PROCESS-NAME,fdm,DIRECT",
    "PROCESS-NAME,aria2c,DIRECT",
    "PROCESS-NAME,Folx,DIRECT",
    "PROCESS-NAME,NetTransport,DIRECT",
    "PROCESS-NAME,uTorrent,DIRECT",
    "PROCESS-NAME,WebTorrent,DIRECT",
    "PROCESS-NAME,aria2c.exe,DIRECT",
    "PROCESS-NAME,BitComet.exe,DIRECT",
    "PROCESS-NAME,fdm.exe,DIRECT",
    "PROCESS-NAME,NetTransport.exe,DIRECT",
    "PROCESS-NAME,qbittorrent.exe,DIRECT",
    "PROCESS-NAME,Thunder.exe,DIRECT",
    "PROCESS-NAME,ThunderVIP.exe,DIRECT",
    "PROCESS-NAME,transmission-daemon.exe,DIRECT",
    "PROCESS-NAME,transmission-qt.exe,DIRECT",
    "PROCESS-NAME,uTorrent.exe,DIRECT",
    "PROCESS-NAME,WebTorrent.exe,DIRECT",
    "DOMAIN,clash.razord.top,DIRECT",
    "DOMAIN,yacd.haishan.me,DIRECT",
    "RULE-SET,private,DIRECT",
    "RULE-SET,direct,DIRECT",
    "RULE-SET,icloud,DIRECT",
    "RULE-SET,apple,DIRECT",
    "RULE-SET,google,DIRECT",
    "RULE-SET,reject,REJECT",
    "RULE-SET,proxy,"+first_name,
    "RULE-SET,telegramcidr,"+first_name,
    "MATCH,DIRECT"]
    
    obj['rules']=rules

    var str_obj=yaml.stringify(obj)
    
    var rule_providers=`rule-providers:
    reject:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
      path: ./ruleset/reject.yaml
      interval: 86400
    icloud:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
      path: ./ruleset/icloud.yaml
      interval: 86400
    apple:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
      path: ./ruleset/apple.yaml
      interval: 86400
    google:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
      path: ./ruleset/google.yaml
      interval: 86400
    proxy:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
      path: ./ruleset/proxy.yaml
      interval: 86400
    direct:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
      path: ./ruleset/direct.yaml
      interval: 86400
    private:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
      path: ./ruleset/private.yaml
      interval: 86400
    gfw:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
      path: ./ruleset/gfw.yaml
      interval: 86400
    greatfire:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
      path: ./ruleset/greatfire.yaml
      interval: 86400
    tld-not-cn:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
      path: ./ruleset/tld-not-cn.yaml
      interval: 86400
    telegramcidr:
      type: http
      behavior: ipcidr
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
      path: ./ruleset/telegramcidr.yaml
      interval: 86400
    cncidr:
      type: http
      behavior: ipcidr
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
      path: ./ruleset/cncidr.yaml
      interval: 86400
    lancidr:
      type: http
      behavior: ipcidr
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
      path: ./ruleset/lancidr.yaml
      interval: 86400`
      str_obj+=rule_providers
    return str_obj
  }
```

大家可以按照自己的需要修改

**Comment by chensimmons** [comment]
大佬好，我不懂JS，请教个问题，因为我订阅链接返回的只有节点，就是只有proxies这一项，没有proxy-groups这一项，所以按上面的代码解析yaml有错误，我应该怎么用JS把proxy-groups添加上去呢？

**Comment by Jie-Qiao** [comment]
> 大佬好，我不懂JS，请教个问题，因为我订阅链接返回的只有节点，就是只有proxies这一项，没有proxy-groups这一项，所以按上面的代码解析yaml有错误，我应该怎么用JS把proxy-groups添加上去呢？

你可以先做个[订阅转换](https://acl4ssr.netlify.app/)，我这个脚本是可以用在转换后的配置的

**Comment by deanhzed** [comment]
Clash_for_Windows
-rule-provider 填入参考
https://lancellc.gitbook.io/clash/clash-config-file/rule-provider
-rule 填入参考
https://docs.cfw.lbyczf.com/contents/parser.html
https://zhuanlan.zhihu.com/p/336003879

**Comment by cccccpppppp** [comment]
根据这个我写了个mixin版的，我增加了**广告拦截功能是否开启**的选项，因为有些场景需要关闭广告拦截 ~~（比如p站）~~ ：
```
module.exports.parse = ({ content, name, url }, { yaml, axios, notify }) => {
  const firstName = content['proxy-groups'][0]['name'];

  const proxyGroups = content['proxy-groups'];
  proxyGroups.push(yaml.parse('{ name: 🛑 广告拦截, type: select, proxies: [ REJECT, DIRECT] }\n'))

  const rules = [
    "PROCESS-NAME,v2ray,DIRECT",
    "PROCESS-NAME,xray,DIRECT",
    "PROCESS-NAME,naive,DIRECT",
    "PROCESS-NAME,trojan,DIRECT",
    "PROCESS-NAME,trojan-go,DIRECT",
    "PROCESS-NAME,ss-local,DIRECT",
    "PROCESS-NAME,privoxy,DIRECT",
    "PROCESS-NAME,leaf,DIRECT",
    "PROCESS-NAME,v2ray.exe,DIRECT",
    "PROCESS-NAME,xray.exe,DIRECT",
    "PROCESS-NAME,naive.exe,DIRECT",
    "PROCESS-NAME,trojan.exe,DIRECT",
    "PROCESS-NAME,trojan-go.exe,DIRECT",
    "PROCESS-NAME,ss-local.exe,DIRECT",
    "PROCESS-NAME,privoxy.exe,DIRECT",
    "PROCESS-NAME,leaf.exe,DIRECT",
    "PROCESS-NAME,Surge,DIRECT",
    "PROCESS-NAME,Surge 2,DIRECT",
    "PROCESS-NAME,Surge 3,DIRECT",
    "PROCESS-NAME,Surge 4,DIRECT",
    "PROCESS-NAME,Surge%202,DIRECT",
    "PROCESS-NAME,Surge%203,DIRECT",
    "PROCESS-NAME,Surge%204,DIRECT",
    "PROCESS-NAME,Thunder,DIRECT",
    "PROCESS-NAME,DownloadService,DIRECT",
    "PROCESS-NAME,qBittorrent,DIRECT",
    "PROCESS-NAME,Transmission,DIRECT",
    "PROCESS-NAME,fdm,DIRECT",
    "PROCESS-NAME,aria2c,DIRECT",
    "PROCESS-NAME,Folx,DIRECT",
    "PROCESS-NAME,NetTransport,DIRECT",
    "PROCESS-NAME,uTorrent,DIRECT",
    "PROCESS-NAME,WebTorrent,DIRECT",
    "PROCESS-NAME,aria2c.exe,DIRECT",
    "PROCESS-NAME,BitComet.exe,DIRECT",
    "PROCESS-NAME,fdm.exe,DIRECT",
    "PROCESS-NAME,NetTransport.exe,DIRECT",
    "PROCESS-NAME,qbittorrent.exe,DIRECT",
    "PROCESS-NAME,Thunder.exe,DIRECT",
    "PROCESS-NAME,ThunderVIP.exe,DIRECT",
    "PROCESS-NAME,transmission-daemon.exe,DIRECT",
    "PROCESS-NAME,transmission-qt.exe,DIRECT",
    "PROCESS-NAME,uTorrent.exe,DIRECT",
    "PROCESS-NAME,WebTorrent.exe,DIRECT",
    "DOMAIN,clash.razord.top,DIRECT",
    "DOMAIN,yacd.haishan.me,DIRECT",
    "RULE-SET,private,DIRECT",
    "RULE-SET,direct,DIRECT",
    "RULE-SET,icloud,DIRECT",
    "RULE-SET,apple,DIRECT",
    "RULE-SET,google,DIRECT",
    "RULE-SET,reject,🛑 广告拦截",
    "RULE-SET,proxy," + firstName,
    "RULE-SET,telegramcidr," + firstName,
    "MATCH,DIRECT"
  ];

  const ruleProviders = yaml.parse(`
    reject:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
      path: ./ruleset/reject.yaml
      interval: 86400
    icloud:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
      path: ./ruleset/icloud.yaml
      interval: 86400
    apple:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
      path: ./ruleset/apple.yaml
      interval: 86400
    google:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
      path: ./ruleset/google.yaml
      interval: 86400
    proxy:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
      path: ./ruleset/proxy.yaml
      interval: 86400
    direct:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
      path: ./ruleset/direct.yaml
      interval: 86400
    private:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
      path: ./ruleset/private.yaml
      interval: 86400
    gfw:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
      path: ./ruleset/gfw.yaml
      interval: 86400
    greatfire:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
      path: ./ruleset/greatfire.yaml
      interval: 86400
    tld-not-cn:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
      path: ./ruleset/tld-not-cn.yaml
      interval: 86400
    telegramcidr:
      type: http
      behavior: ipcidr
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
      path: ./ruleset/telegramcidr.yaml
      interval: 86400
    cncidr:
      type: http
      behavior: ipcidr
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
      path: ./ruleset/cncidr.yaml
      interval: 86400
    lancidr:
      type: http
      behavior: ipcidr
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
      path: ./ruleset/lancidr.yaml
      interval: 86400
  `);

  const extra = {
    'proxy-groups': proxyGroups,
    rules,
    'rule-providers': ruleProviders
  }

  return { ...content, ...extra };
}
```

**Comment by LuckilyCrazy** [comment]
哇，谢谢各位大佬！！从v2rayN换到了CFW，因为发现没法直接代理一些不走系统代理的软件，CFW的的TUN模式的确好用。不过规则居然是机场提供的，用起来总觉得不对，自己只需要简单的黑白名单类似的规则，于是摸到了这里。小白研究了好久，也搞了个parser，直接复制到预处理配置里，更新订阅就好，会替换整个服务商的规则，可以根据自己的需求改，Clash for Windows的。

```
parsers: # array
  # - reg: .*$ 匹配所有订阅，或  - url: https://example.com/profile.yaml 指定订阅
  - reg: .*$
  #删除服务商提供的策略组和规则
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const { 'Rule': rules = [], 'Proxy Group':groups = [] } = rawObj
        return yaml.stringify({ ...rawObj, 'proxy-groups': groups, rules })
      } 
  #建立自己的配置
    yaml:
      prepend-proxy-groups: # 添加策略组
        - name: 🔰 选择代理 
          type: select
        - name: ♻️ 自动选择
          type: url-test
          url: http://www.gstatic.com/generate_204
          interval: 300
          tolerance: 50
        - name: 🛑 广告拦截
          type: select
          proxies:
            - REJECT
            - DIRECT
            - 🔰 选择代理
        - name: 🐟 漏网之鱼
          type: select
          proxies:
            - DIRECT
            - 🔰 选择代理
      commands:
        - proxy-groups.🔰 选择代理.proxies=[]proxyNames # 向指定策略组添加订阅节点名
        - proxy-groups.🔰 选择代理.proxies.0+DIRECT
        - proxy-groups.🔰 选择代理.proxies.1+♻️ 自动选择
        - proxy-groups.♻️ 自动选择.proxies=[]proxyNames

      prepend-rules: #添加规则
        - PROCESS-NAME,v2ray,DIRECT
        - PROCESS-NAME,xray,DIRECT
        - PROCESS-NAME,naive,DIRECT
        - PROCESS-NAME,trojan,DIRECT
        - PROCESS-NAME,trojan-go,DIRECT
        - PROCESS-NAME,ss-local,DIRECT
        - PROCESS-NAME,privoxy,DIRECT
        - PROCESS-NAME,leaf,DIRECT
        - PROCESS-NAME,v2ray.exe,DIRECT
        - PROCESS-NAME,xray.exe,DIRECT
        - PROCESS-NAME,naive.exe,DIRECT
        - PROCESS-NAME,trojan.exe,DIRECT
        - PROCESS-NAME,trojan-go.exe,DIRECT
        - PROCESS-NAME,ss-local.exe,DIRECT
        - PROCESS-NAME,privoxy.exe,DIRECT
        - PROCESS-NAME,leaf.exe,DIRECT
        - PROCESS-NAME,Surge,DIRECT
        - PROCESS-NAME,Surge 2,DIRECT
        - PROCESS-NAME,Surge 3,DIRECT
        - PROCESS-NAME,Surge 4,DIRECT
        - PROCESS-NAME,Surge%202,DIRECT
        - PROCESS-NAME,Surge%203,DIRECT
        - PROCESS-NAME,Surge%204,DIRECT
        - PROCESS-NAME,Thunder,DIRECT
        - PROCESS-NAME,DownloadService,DIRECT
        - PROCESS-NAME,qBittorrent,DIRECT
        - PROCESS-NAME,Transmission,DIRECT
        - PROCESS-NAME,fdm,DIRECT
        - PROCESS-NAME,aria2c,DIRECT
        - PROCESS-NAME,Folx,DIRECT
        - PROCESS-NAME,NetTransport,DIRECT
        - PROCESS-NAME,uTorrent,DIRECT
        - PROCESS-NAME,WebTorrent,DIRECT
        - PROCESS-NAME,aria2c.exe,DIRECT
        - PROCESS-NAME,BitComet.exe,DIRECT
        - PROCESS-NAME,fdm.exe,DIRECT
        - PROCESS-NAME,NetTransport.exe,DIRECT
        - PROCESS-NAME,qbittorrent.exe,DIRECT
        - PROCESS-NAME,Thunder.exe,DIRECT
        - PROCESS-NAME,ThunderVIP.exe,DIRECT
        - PROCESS-NAME,transmission-daemon.exe,DIRECT
        - PROCESS-NAME,transmission-qt.exe,DIRECT
        - PROCESS-NAME,uTorrent.exe,DIRECT
        - PROCESS-NAME,WebTorrent.exe,DIRECT
        - DOMAIN,clash.razord.top,DIRECT
        - DOMAIN,yacd.haishan.me,DIRECT
        - RULE-SET,private,DIRECT
        - RULE-SET,reject,🛑 广告拦截
        - RULE-SET,icloud,DIRECT
        - RULE-SET,apple,DIRECT
        - RULE-SET,google,DIRECT
        - RULE-SET,telegramcidr,🔰 选择代理
        - RULE-SET,tld-not-cn,🔰 选择代理
        - RULE-SET,proxy,🔰 选择代理
        - RULE-SET,gfw,🔰 选择代理
        - RULE-SET,greatfire,🔰 选择代理
        - RULE-SET,direct,DIRECT
        - RULE-SET,lancidr,DIRECT
        - RULE-SET,cncidr,DIRECT
        - GEOIP,,DIRECT
        - GEOIP,CN,DIRECT
        - MATCH,🐟 漏网之鱼
        
      mix-rule-providers: # 添加规则集
        reject:
          type: http
          behavior: domain
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
          path: ./ruleset/reject.yaml
          interval: 86400
        icloud:
          type: http
          behavior: domain
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
          path: ./ruleset/icloud.yaml
          interval: 86400
        apple:
          type: http
          behavior: domain
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
          path: ./ruleset/apple.yaml
          interval: 86400
        google:
          type: http
          behavior: domain
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
          path: ./ruleset/google.yaml
          interval: 86400
        proxy:
          type: http
          behavior: domain
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
          path: ./ruleset/proxy.yaml
          interval: 86400
        direct:
          type: http
          behavior: domain
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
          path: ./ruleset/direct.yaml
          interval: 86400
        private:
          type: http
          behavior: domain
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
          path: ./ruleset/private.yaml
          interval: 86400
        gfw:
          type: http
          behavior: domain
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
          path: ./ruleset/gfw.yaml
          interval: 86400
        greatfire:
          type: http
          behavior: domain
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
          path: ./ruleset/greatfire.yaml
          interval: 86400
        tld-not-cn:
          type: http
          behavior: domain
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
          path: ./ruleset/tld-not-cn.yaml
          interval: 86400
        telegramcidr:
          type: http
          behavior: ipcidr
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
          path: ./ruleset/telegramcidr.yaml
          interval: 86400
        cncidr:
          type: http
          behavior: ipcidr
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
          path: ./ruleset/cncidr.yaml
          interval: 86400
        lancidr:
          type: http
          behavior: ipcidr
          url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
          path: ./ruleset/lancidr.yaml
          interval: 86400
```
