### ISSUE TITLE
对于Clash Verge我只想要让“直连域名列表”走直连，而不处理其他的列表，该如何实现？

### ISSUE THREAD

**Issue by NianBroken** [Loyalsoldier/clash-rules#287]
我在[隔壁](https://github.com/clash-verge-rev/clash-verge-rev/issues/1108)提了issues，但是隔壁的人都好凶，说话语气很冲。
我也是开发者，我觉得大家应该心平气和的交流。
至少别人在我的项目里提issues的时候，我会认真给别人解答，直到对方消除自己的疑惑。
无论如何我都不会那么冲的对别人说出“[**让你看文档听不听得懂人话**](https://github.com/clash-verge-rev/clash-verge-rev/issues/1108#issuecomment-2143428488)”这种话

所以我想来这边再问一遍。

就是给的示例有其他规则，如“`广告域名列表`”、“`GFWList 域名列表`”、“`中国大陆 IP 地址列表`”等等，但是我只想要让`直连域名列表`走直连，而不处理其他的列表。

我只想要让`https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt`内的所有域名都走直连，而不处理其他的列表，该如何实现？

我下图中的配置信息是正确的吗？

![image](https://github.com/Loyalsoldier/clash-rules/assets/57057288/ff6ec203-5f71-474b-a44f-fb8c43e2be28)

![image](https://github.com/Loyalsoldier/clash-rules/assets/57057288/106d7c0e-e01d-43cd-8959-92125468c4db)

**Comment by NianBroken** [comment]
我在提出这个issues之前已经翻看过本项目的issues，以及隔壁的issues了。并且也在谷歌搜过，但是没有找到有用的内容。

我的需求就是我只想要让https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt内的所有域名都走直连，而不处理其他的列表。

**Comment by NianBroken** [comment]
@1523789353

**Comment by NianBroken** [comment]
@Loyalsoldier

**Comment by NianBroken** [comment]
@caiysmy

**Comment by NianBroken** [comment]
@1523789353 @MurphyZX @Loyalsoldier @caiysmy @mo-han @DustinWin 大佬们能帮忙看看吗

**Comment by mo-han** [comment]
最后再加一行，把所有其他的map到proxy，参照其他那些配置里面最后一条rule

**Comment by NianBroken** [comment]
@mo-han 是这样吗？

![image](https://github.com/Loyalsoldier/clash-rules/assets/57057288/ded91f61-dab6-42d6-9550-4a1d05ed48e0)

**Comment by NianBroken** [comment]
@mo-han 是这样吗？

![image](https://github.com/Loyalsoldier/clash-rules/assets/57057288/375aaacc-f94a-4e04-a01d-7670cb49d136)

**Comment by DustinWin** [comment]
> @mo-han 是这样吗？
> 
> ![image](https://private-user-images.githubusercontent.com/57057288/335841274-375aaacc-f94a-4e04-a01d-7670cb49d136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMDg4MjUsIm5iZiI6MTcxNzMwODUyNSwicGF0aCI6Ii81NzA1NzI4OC8zMzU4NDEyNzQtMzc1YWFhY2MtZjk0YS00ZTA0LWEwMWQtNzY3MGNiNDlkMTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDA2MDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjFjNjZkMWFiNTI0ZGVmNzVjZmJjMjZmNDZhNjM5ZDZkZjIwNTZjYjJmMWIwN2ZiOTNiNjM1OGFlNWYzZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dn23st6tulgnYlmJWPUnJ_MSL9O28S4ojtnenXyesjc)

你说的“不处理其他的列表”如果指的是仅让 `direct.txt` 列表内的域名走直连，其它所有域名或 IP 走代理的话这样配置是可以的。

**Comment by caiysmy** [comment]
建议使用GEO文件分流
  - GEOSITE,CN,direct
  - GEOIP,CN,direct
  - MATCH,Proxy

**Comment by NianBroken** [comment]
> > @mo-han 是这样吗？
> > ![image](https://github.com/Loyalsoldier/clash-rules/assets/57057288/375aaacc-f94a-4e04-a01d-7670cb49d136)
> 
> 你说的“不处理其他的列表”如果指的是仅让 `direct.txt` 列表内的域名走直连，其它所有域名或 IP 走代理的话这样配置是可以的。

@DustinWin 我在使用了该配置后，访问`direct.txt`列表内的域名，在clash的`连接`板块中查看时，域名走的依然是代理而不是直连。
已经启动Merge了，并且也尝试过关闭clash再重新开启，但依然是走的代理而不是直连。

**Comment by NianBroken** [comment]
> 建议使用GEO文件分流
> 
> * GEOSITE,CN,direct
> * GEOIP,CN,direct
> * MATCH,Proxy

@caiysmy 可以给我一个完整的配置文件示例吗

**Comment by caiysmy** [comment]
`geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
rules:
  - GEOSITE,CN,direct
  - GEOIP,CN,direct
  - MATCH,Proxy`

**Comment by caiysmy** [comment]
```
geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
rules:
  - GEOSITE,CN,direct
  - GEOIP,CN,direct
  - MATCH,Proxy
```
