### ISSUE TITLE
proxy-prodviders报错：config.yaml: initial proxy provider CNIX error: yaml: unmarshal errors:

### ISSUE THREAD

**Issue by darcydai** [Loyalsoldier/clash-rules#295]
我使用的hiden分支的config.yaml 覆盖的我本地的config.yaml 只改了 proxy-providers 部分 配置如下
```
proxy-providers:
  CNIX:
    type: http
    url: "https://04.xxx.xyz/api/v1/client/subscribe?token=abc"
    path: ./cnix.yaml
    interval: 7200
```
报错信息为
```
config.yaml: initial proxy provider CNIX error: yaml: unmarshal errors:
line 1: cannot unmarshal !!str `dHJvamF...` into provider.ProxySchema
```
我访问的订阅链接返回的是一个base的字符串，不知道是不是哪里配置的不对。
期待回复，万分感谢。
