### ISSUE TITLE
能否将局域网内设备的clash 端口添加为 http 类型的节点

### ISSUE THREAD

**Issue by p1aintiff** [Loyalsoldier/clash-rules#329]
192.168.2.4上开了一个clash，7890端口能用

我想在路由器上（192.168.2.1）也运行一个clash将需要代理的流量转发到2.4这台设备上，类似旁路由科学上网
路由器性能不够，2.4这台设备可能失联。
我想通过`  - { name: LOCAL, type: fallback,proxies: ['http',DIRECT] }`
这种代理组实现自动切换
可能的配置
```
proxies:
  - name: "http"
    type: http
    server: 192.268.2.4
    port: 7890
# 代理组
proxy-groups:
  - { name: LOCAL, type: fallback,proxies: ['http',DIRECT] }
  - 
# 规则列表
rule-providers:
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

rules:
  - RULE-SET,gfw,LOCAL
  - MATCH,DIRECT
```
