### ISSUE TITLE
在ClashX中使用Proxy Provider搭配本规则的参考资料

### ISSUE THREAD

**Issue by shikkoku** [Loyalsoldier/clash-rules#54]
https://donnadie.top/manage-clashx-custom-config/

教程不是我写的，今天在研究本项目不影响自动更新节点下被重新覆盖的解决办法参考了这份资料，对我有所帮助，希望也能给大家带来个参考

主要是这一段和教程给的参考设置有些不同

**该项目提供了每天更新的较为完善的配置文件，且不同部分的规则都分文件管理，非常清晰

项目说明中已经提供了 rule-providers 的配置方法，这里指出几个注意事项：

该规则集使用了三个策略组：DIRECT 、 REJECT 、 PROXY 。前面两个是clash内核自带的策略组，第三个则需要自己在 proxy-groups 中添加。也就是说 proxy groups 字段中至少应该具备如下配置：**

```
proxy-groups:
  - name: PROXY
    type: select
    use:
      - foo
      - bar
    proxies:
      - DIRECT

```

如要将普通带规则的Clash订阅转换成Proxy Provider形式

参考了此项目提供的工具

https://github.com/qier222/proxy-provider-converter
