### ISSUE TITLE
有点小疑问，烦请大神解答一二

### ISSUE THREAD

**Issue by AdoShan** [Loyalsoldier/clash-rules#66]
我用了rule-providers，书写如下
```
rule-providers:
    TelegramRule:
        type: http
        behavior: classical
        url: "https://raw.githubusercontent.com/AdoShan/Shan/master/Ruleset/Clash/Telegram.yaml"
        path: ./ruleset/Telegram.yaml
        interval: 86400
```
存在策略组`Telegram`，然后我将这一条规则引用命名为`TelegramRule`，我怎么才能让他走命名为`Telegram`的策略组

我CFW中查看Rules，并没有看到引用的相关规则，这是不是就说明我这个引用没生效
