### ISSUE TITLE
希望增加微软和苹果的所有规则，方便选择！

### ISSUE THREAD

**Issue by aqbjqtd** [Loyalsoldier/clash-rules#69]
希望增加微软和苹果的所有规则，方便自主选择代理和直连！

**Comment by mashirozx** [comment]
FYI
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Microsoft.list

**Comment by Loyalsoldier** [comment]
请期待项目重构。

**Comment by XMuli** [comment]
已阅 #6 ，能够将 微软 microsoft 的规则也列举出来，直接引用？便于直接需要时切换。

希望下载大文件时候，可以直连，访问部分网页时候，采用代理

**Comment by Sugimoto-Dev** [comment]
> 已阅 #6 ，能够将 微软 microsoft 的规则也列举出来，直接引用？便于直接需要时切换。
> 
> 希望下载大文件时候，可以直连，访问部分网页时候，采用代理

有同样的需求, 如果可以的话, 请帮忙把microsoft从proxy中提出来, 单独提供一个文件, 拜托!

**Comment by XMuli** [comment]
感觉可用 `https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list` ，但添加如下时候，报错；还在摸索中 @Sugimoto-Dev ,供参考

```yaml
      mix-rule-providers:
        microsoft:
            type: http
            behavior: ipcidr
            url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
            path: ./ruleset/microsoft.yaml
            interval: 86400
```
![image](https://github.com/Loyalsoldier/clash-rules/assets/33887845/4025e002-2374-4c0c-9ea0-b683a062046c)

**Comment by xuchuang199636** [comment]
> 感觉可用 `https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list` ，但添加如下时候，报错；还在摸索中 @Sugimoto-Dev ,供参考
> 
> ```yaml
>       mix-rule-providers:
>         microsoft:
>             type: http
>             behavior: ipcidr
>             url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
>             path: ./ruleset/microsoft.yaml
>             interval: 86400
> ```
> 
> ![image](https://user-images.githubusercontent.com/33887845/240788060-4025e002-2374-4c0c-9ea0-b683a062046c.png)

@XMuli 我的解决方案是：下载Microsoft.list文件，然后上传到对象存储服务器（七牛云对象存储），从对象存储服务器中获取文件直链替代上面的链接。【关键词】云存储，文件直链。

**Comment by EarOfWheat** [comment]
> 感觉可用 `https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list` ，但添加如下时候，报错；还在摸索中 [@Sugimoto-Dev](https://github.com/Sugimoto-Dev) ,供参考
> 
>       mix-rule-providers:
>         microsoft:
>             type: http
>             behavior: ipcidr
>             url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
>             path: ./ruleset/microsoft.yaml
>             interval: 86400
> ![image](https://github.com/Loyalsoldier/clash-rules/assets/33887845/4025e002-2374-4c0c-9ea0-b683a062046c)

我用clash-verge，用url会报503，所以自己下来参考[这个](https://clash.wiki/configuration/outbound.html#proxy-providers-%E4%BB%A3%E7%90%86%E9%9B%86)操作，以下是我的可用代码。
```yaml
rule-providers:
  microsoft:
    type: file
    behavior: classical
    path: /ruleset/microsoft.yaml

  # 其他配置...
```
