### ISSUE TITLE
proxy [PROXY] not found 错误

### ISSUE THREAD

**Issue by lyjslyj** [Loyalsoldier/clash-rules#79]
```
mixed-port: 8970
allow-lan: false
external-controller: 127.0.0.1:1521

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.tx\
      t"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.t\
      xt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr\
      .txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications\
      .txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
```
 以上是我按照 readme.md 中在 config.yaml 中添加的内容, 重新启动 CFW 后, 报错如下:
![Snipaste_2022-04-10_07-39-38](https://user-images.githubusercontent.com/60648876/162595206-b466555f-7023-4212-ae8b-354bfa8e1871.png)
#68 中曾经提到这个问题, 但我将 PROXY 替换为 Proxy 后, 并没有发生任何变化.

以下是 log 的内容:
```
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider proxy"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider applications"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider google"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider tld-not-cn"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider private"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider icloud"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider telegramcidr"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider lancidr"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider greatfire"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider cncidr"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider apple"
time="2022-04-10T07:47:01+08:00" level=info msg="Start initial rule provider direct"
time="2022-04-10T07:47:02+08:00" level=info msg="Start initial rule provider gfw"
time="2022-04-10T07:47:02+08:00" level=info msg="Start initial rule provider reject"
time="2022-04-10T07:47:02+08:00" level=fatal msg="Parse config error: rules[8] [RULE-SET,proxy,PROXY] error: proxy [PROXY] not found"
```
